language: node_js
node_js: 10
deploy:
  provider: heroku
  api_key:
    secure: Q2kDmVgsw1XRwiSEyrr9rWr+Hv1PH8hhmoNzqka0EOU0H7RNIt0dkpqCNvO0cxSZBW3ve7LlxijVDiabYbKZVek/txRjkSBh9/2RcYvjGcz5vT1tczuEii41AEoQs6J2U8zUs70kZNC2+cl0fuQeGL5dUBD9RhXL98T4+cpS4v1pH9argO7JrYsBCWBjxziExMQVThQBnTftnqBFq9N+RUJdFfXtm1AM64dA7S6NUSWr9oZ7bnGc3feW+wsemvY7rRACk4N5x43ttdoJqWEyZa8UQJl3vSL7bpNZDCzT5Xs5/x6zl1kK6iOvRgblWOlT7yYUZztzdorJLc1E1mV1CN1JApvUssS+B/13v0q6pP3XQy80uGEGs5MyjUqGiOc2X3dDDMmAN/mve0LSuQvKDBu8AEtYTYaNEh97KI+LxjdUe2JCCt0JigKutkWrEuZFIhPlDuFPCRODXN6IuSnTcJzpHNeuXaeOmEKeM08IAkiztKmZNtsOO0pgBBvYm9/gHMZUMLrs/Z+6RLGQe7ad87sqbqoXiA2M+vxNmZOaSXZd7AQmtzt0GadV8JkhtyCcCNJTwpDTogiX8ZPTqD+K/zJVLb9dm6CgtSLZV7A6CDjBYwUQ3dJH1UvdPW5uyy0vEDVtJB2l55UA0SKO6TVfMkQnu0lwKicmacV46f8syyY=
