language: node_js
node_js: 10
deploy:
  app: www-ajessen-com
  on:
    branch: master
  provider: heroku
  api_key:
    secure: TdFsbh65X+v/ZYGH/hbH3MxUKOI+8KYHB1K1JfXBm8iYtJsDq4EASfarVXCqqWmur5mnMDIwYe3gbFLVylxhWRz3wlTGfydpHeYNpp07Woka4WDvUGhfgdkCH6xDR8l1vMmlcwy5WDIJWR7X1NeXX5aSdOyK6FkY2f5NskwoPGkabw1l3joWjM9zHaVng1X76gnb/ff2Ut0TRiblpLEoi7I7Fj3UZUaVhbe5BYv7SVfKuVS9ANrcrldSguwWJx21om7Lo7hlecZ3Lp/KjIb1Uxn5DRRJ1C8dmx31vtY096ndteuUqn8kSc/SVnO6Q1ric0l6wItQMKFf6s7dhuHYPE4uPcql8u3g+QeGRvkyKSS0fv9DKdvpeqspjWE+yqjKYZssnaSp+yH2xQWRcJ1jSCXjSYoYD3VI+M4/XYsQiN6I8JXE2Sxz0OO8cdB8Ypu4WDYKJyeuFHLgSO3+R58nHMIDcWL7GCMnRmtI2Iy5u3F3iuupc9fJ3WvBwEA9Dt81Ciq1zOEJwGlJ/CKs0hD5tQkJQ6OYJV8XxAS8/oRKlDje4UwnaGi2T/482UItl7Abs8BPHe1WWYlir+11uFkUlrP2X7Fs8aHd/m4fFJ7pSI48QBkDSo5gCPsnygKKPZApJDt431asLgrPnsaUMggK4uZNkS0m329hvVei3+gDKC4=
