language: node_js
node_js: 10
deploy:
  provider: heroku
  api_key:
    secure: UQUrz92LvkKTc5dRGx8ftBdKRz5CXQjYGORGP/CttOIoxbHyoyAdTgbcItbxn8R2gCWWjYhG/TpHpql27fBIWjmp5NsbTMiLwTLwy2OhRiuEqnq9B4aqtzahc09CsLt9yk/VEg2Teyw/uPa7ioA9UfTM1KX0FO5cewHRFD19PT4AZKATiNUMK0nTQefsq5Gf7cWnUWchi9db/BfZoYz1XBvt7mBrtkj7urB2sBKAHJkTKJsW874Zlq3Uaih7ZgdV6tU9Bg6VEAsWWOJZr/LkWE/gD3QqzhV9sHP0YRw8CjkVmZ7r6QgbVczT5g5tvGi5cmVK1Qpx5KT9FoN3VA4oetfbywuMjCehExoEy3f2y0VieNhD2udBYBE+J/zvqOQ/AcV+EOBRKvdLNep6YB5CLu+5s052lkYjcJKXfz+b/cebZfniYMHzEguAKW54ys7LkayEYkZS78f413IKzyh3w0lG8+AfxIwXzb3+QAVFrgUhLic6it3KhwtibUnKa9tqX8b5Sw5/ipMsv3l9072k4mxIaYad14OwiRqN9h7UVXrJEsxW/i1b90y1JEgJZwPbkrPB7Q9+dC67scpTNnondNOWPC/WLkYHcMhBZidHnDlFNromtxYRhC5jcTJl4WugcwOHULtCuwhDFgrnCsVbaOYS+DoZgOGclj+ldCHYyFI=
