language: node_js
node_js: 10
deploy:
  on:
    branch: master
  provider: heroku
  api_key:
    secure: yDkd6TCWW2SJ+bxzfQEtY5LjOWF2QTLkZHrC18ZGDVAYUFtwd2u8Dy9FDYpMd+n8+1n5xrSpm2o4w0661GXgXJupFmeRjw0jtRQyf5I3CDJ0LtXVUUIHk940cdNM5cpZMj84FzvlzQjgve/Bytno0AsZtFMGRqY3+x4XuJd2/XcCXGCDy3I/rOh6NFnaDd6A+VeXZ+e8Gf6WOaDC3IAaimZTD63N9GmmTYE47+ij6RH2dCrdvPFoqLIUrJnKEXFweOvGShNXzedfd+95mz6YSKJdlg5RXkIOdhhEZAZ+gMQY3kEuNyGdWW4aewyWdSufKmuk6Hr7qzkZ2+lmgo1pcJZNUlQZ9lPoW6uerYuRgqabk2PQqjwcuENoOBdfniaqFva8UZLsLlv3C6l4OVxbDCULMU+fENt6IwxXSUTXEYz2yEXXPGpMyHgJnhH4uVH0oFjQk2P+13Je9HYyVA1tIMZq1BB13o/ld/GXIpD8A+Hdmoy7qbxfpGWxk1Rw5EgjANe22cdIADK6jfv2kg6rfRhKkGHxDbktOslTPkYvpgE86w3r2ECmGlj5G6iRXhaNmxN6Dn+YFZJ9ymVPqON6YJ97TX/VMOkQZa24X0kW5gHKy7TiSyYHqFKpS1JdT5kdVBvN0HetWGri/rUKSwDJB2SVqJUPI72wGrr3+BcufQM=
