import React from 'react'

class About extends React.Component {
    render() {
        return (
            <main id="about">
                <h1>About</h1>
                <img src={require('../assets/andrewjessentyler.jpg')} alt="Andrew Jessen-Tyler"/>
                <p>My name is Andrew Jessen-Tyler. I created AJessen (sole proprietorship) to allow an easy place to advertise my skills to both potential clients for side-work, but mainly as a portfolio website for potential employers. I've been into technology and computers as far back as I can remember. I even had a computer when I was 4 (that I mainly just played pinball on) and I remember even back then being super excited being able to help family members with technology. It could be something simple like helping my great-grandma work her laptop or something more complex like helping my dad with wiring the speakers at his new apartment.<br/>
                I started programming in Middle School, using "Game Maker" and had already become known to my classmates and even my teachers as a good resource to go to for tech issues. I became a student aid to our computer's teacher in 8th grade and actually was able to actually assist with real problems students had, rather than just handling some clerical work. It was also around this time my dad (along with help from other relatives) bought me all the parts to build my first computer. While he helped me somewhat, most of the work was on me to figure out just from reading the instruction manuals. I would go on to upgrade everything in it over time, including the case, and coming up with "dream rigs" or playing PC Building Simulator is still one of my favorite things to do.</p>
                <p>During High School, I already was starting to figure out I wanted to do programming. I had already been known as the "tech guy" and even took 2 semesters of Web Design. Hardware was nice, but I didn't want to create hardware too much. Software always seemed more like my style. So when I heard Intel was teaching a circuits class at my high school, I HAD to take it. Most of it was simple and standard things you could be taught in any classroom, but by the end we were actually using the software Intel uses to design circuit boards. They would give us a bunch of different logic gates we were to make circuit boards for, with the first few being basic and the last few being insanely large and complex. Me and a couple of my other passionate classmates were always in a race to stay in the lead.<br/>
                After High School, I went to UNC in Greeley, CO, studying for a Software Engineering B.S. for 3 semesters, before having to leave due to finnancial concerns. It gave me a taste of Python and Java. Someday, I do plan to go back and complete it. But until then, I had to find another way to learn programming. I did some self teaching as I worked for a while, but I consider my time with Thinkful to be the most helpful. I was able to relearn the HTML and CSS I had learned in High School and then got to continue into Javascript, JSX, and Node.js. React was alright, I learned to do some cool stuff with it. But when we started learning Express.js and PostgreSQL, that became my forte, and still is to this day. So, ideally I'd like to be a back-end web developer. I feel my way of thinking really accels back there.<br />
                I'm now looking for my first real programming job, so I can expand my skills and contribute to the internet of things. My dream is to work in some fashion with developing Artificial Intelligence (AI) and/or Full Dive Virtual Reality, (yes, like Sword Art Online).<br /> <br />
                To move into the more personal details, I was born in York, NE but have lived in Fort Collins, CO most of my life. I do plan to live in Northern Colorado for the rest of my life. My favorite animals are dogs, cats, and bunnies. I grew up around each of them. Outside of programming, I enjoy immersing myself in even more technology. I love to play video games, from the retro Donkey Kong Country 2 on the SNES, to the crazy open world of Saints Row IV. As mentioned, I also like building "dream rigs", but I also watch a lot of informational Youtube Channels, such as TechQuickie (Linus Tech Tips), Numberphile, ASAPScience, Tom Scott, Mark Rober, and Game Theory. Outside of informational Youtube Channels, I also watch tons of anime and anime-inspired shows, such as RWBY, Chihayafuru, and Sword Art Online. I get my fill of "normal" TV from shows like House M.D., The Office, and How I Met Your Mother. Some of the less informational Youtube Channels I watch include Markiplier, Alpharad, Scott The Woz, and Schaffrilla's Productions. Sports don't do much for me except the LCS, League of Legends' E-Sports. I also grew up doing tons of Choir and Musical Theater, and music still holds a place in my heart. I'd love to arrange a song and direct a High School choir sometime.<br />
                </p>
            </main>
        )
    }
}

export default About